# Game Theory

This notebook contains code examples referring to the Game Theory chapter of "Applied Mathematics with Open-Source Software: Operational Research Problems
with Python and R".

First we write a function that returns a game.

In [1]:
import nashpy as nash
import numpy as np


def get_game(profits, offset=0):
    """Return the game object with a given offset when 3 taxis are
    provided.

    Args:
        profits: a matrix with expected profits
        offset: a float

    Returns:
        A nashpy game object
    """
    new_profits = np.array(profits)
    new_profits[2] += offset
    return nash.Game(new_profits, new_profits.T)

The game for the problem in the chapter is given by:

In [2]:
profits = np.array(
    (
        (1, 1 / 2, 1 / 3),
        (3 / 2, 19 / 20, 1 / 2),
        (5 / 3, 4 / 5, 17 / 20),
    )
)
game = get_game(profits=profits)
print(game)

Bi matrix game with payoff matrices:

Row player:
[[1.         0.5        0.33333333]
 [1.5        0.95       0.5       ]
 [1.66666667 0.8        0.85      ]]

Column player:
[[1.         1.5        1.66666667]
 [0.5        0.95       0.8       ]
 [0.33333333 0.5        0.85      ]]


Next we write a function that gives the Nash equilibria for a game.

In [3]:
def get_equilibria(profits, offset=0):
    """Return the equilibria for a given offset when 3 taxis are
    provided.

    Args:
        profits: a matrix with expected profits
        offset: a float

    Returns:
        A tuple of Nash equilibria
    """
    game = get_game(profits=profits, offset=offset)
    return tuple(game.support_enumeration())

So the equilibria for the considered game are:

In [4]:
equilibria = get_equilibria(profits=profits)
for eq in equilibria:
    print(eq)

(array([0., 1., 0.]), array([0., 1., 0.]))
(array([0., 0., 1.]), array([0., 0., 1.]))
(array([0. , 0.7, 0.3]), array([0. , 0.7, 0.3]))


Finding the offset that gives only one Nash equilibrium.

In [5]:
offset = 0
while len(get_equilibria(profits=profits, offset=offset)) > 1:
    offset += 0.01

gives

In [6]:
print(round(offset, 2))

0.15


with that equilibrium being:

In [7]:
print(get_equilibria(profits=profits, offset=offset))

((array([0., 0., 1.]), array([0., 0., 1.])),)
